const Enum = require("enum");

module.exports = new Enum({
	TOX_ERR_NEW_OK: 0,
	TOX_ERR_NEW_NULL: 1,
	TOX_ERR_NEW_MALLOC: 2,
	TOX_ERR_NEW_PORT_ALLOC: 3,
	TOX_ERR_NEW_PROXY_BAD_TYPE: 4,
	TOX_ERR_NEW_PROXY_BAD_HOST: 5,
	TOX_ERR_NEW_PROXY_BAD_PORT: 6,
	TOX_ERR_NEW_PROXY_NOT_FOUND: 7,
	TOX_ERR_NEW_LOAD_ENCRYPTED: 8,
	TOX_ERR_NEW_LOAD_BAD_FORMAT: 9
}, {name: "TOX_ERR_NEW"});