enum ToxErrNew {
	TOX_ERR_NEW_OK,
	TOX_ERR_NEW_NULL,
	TOX_ERR_NEW_MALLOC,
	TOX_ERR_NEW_PORT_ALLOC,
	TOX_ERR_NEW_PROXY_BAD_TYPE,
	TOX_ERR_NEW_PROXY_BAD_HOST,
	TOX_ERR_NEW_PROXY_BAD_PORT,
	TOX_ERR_NEW_PROXY_NOT_FOUND,
	TOX_ERR_NEW_LOAD_ENCRYPTED,
	TOX_ERR_NEW_LOAD_BAD_FORMAT
};

export default ToxErrNew;